server:
  port: 8762

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-service?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:matim198}
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  publicKey: classpath:public-key.pem
  privateKey: classpath:pkcs8.key

