server:
  port: 8764

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product-service?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:matim198}
  jpa:
    hibernate:
      ddl-auto: update